# Generated by Django 5.1.6 on 2026-01-15 08:55

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('camera_id', models.CharField(max_length=50)),
                ('camera_name', models.CharField(blank=True, max_length=256, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_detections', models.IntegerField(default=0)),
                ('total_landings', models.IntegerField(default=0)),
                ('total_takeoffs', models.IntegerField(default=0)),
                ('total_alerts', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AircraftDetection',
            fields=[
                ('detection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track_id', models.IntegerField(default=0, help_text='Tracking ID from the tracker')),
                ('detection_type', models.CharField(choices=[('aircraft', 'Aircraft'), ('helicopter', 'Helicopter'), ('drone', 'Drone'), ('unknown', 'Unknown')], default='aircraft', max_length=20)),
                ('action', models.CharField(choices=[('landing', 'Landing'), ('takeoff', 'Takeoff'), ('taxiing', 'Taxiing'), ('parked', 'Parked'), ('flying', 'Flying'), ('hovering', 'Hovering'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('aircraft_type', models.CharField(blank=True, max_length=100, null=True)),
                ('aircraft_registration', models.CharField(blank=True, max_length=50, null=True)),
                ('flight_number', models.CharField(blank=True, max_length=20, null=True)),
                ('airline', models.CharField(blank=True, max_length=100, null=True)),
                ('runway', models.CharField(blank=True, max_length=20, null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in knots', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in feet', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Heading in degrees', null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('camera_id', models.CharField(max_length=50)),
                ('camera_name', models.CharField(blank=True, max_length=256, null=True)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('video_path', models.CharField(blank=True, max_length=500, null=True)),
                ('bbox_x1', models.IntegerField(default=0)),
                ('bbox_y1', models.IntegerField(default=0)),
                ('bbox_x2', models.IntegerField(default=0)),
                ('bbox_y2', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('detection_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-detection_time'],
                'indexes': [models.Index(fields=['detection_type'], name='aircraft_de_detecti_2be9a2_idx'), models.Index(fields=['action'], name='aircraft_de_action_3cf615_idx'), models.Index(fields=['detection_time'], name='aircraft_de_detecti_d761cf_idx'), models.Index(fields=['camera_id'], name='aircraft_de_camera__040ae1_idx'), models.Index(fields=['status'], name='aircraft_de_status_e81355_idx'), models.Index(fields=['severity'], name='aircraft_de_severit_b62d0a_idx')],
            },
        ),
    ]
