# Generated by Django 5.1.6 on 2026-01-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftdetection',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether the alert has been viewed'),
        ),
    ]
