# Generated by Django 5.1.6 on 2026-01-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft_detection', '0002_add_is_read_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftdetection',
            name='crop_video_path',
            field=models.CharField(blank=True, help_text='Path to cropped/zoomed aircraft video', max_length=500, null=True),
        ),
    ]
