# Generated by Django 5.1.6 on 2026-01-15 08:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('camera_type', models.CharField(choices=[('ip', 'IP Camera'), ('rtsp', 'RTSP Stream'), ('usb', 'USB Camera'), ('file', 'Video File')], default='rtsp', max_length=20)),
                ('rtsp_link', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('is_healthy', models.BooleanField(default=True)),
                ('is_processing', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, null=True)),
                ('roi_points', models.JSONField(blank=True, default=list, help_text='List of [x,y] coordinates defining the ROI polygon', null=True)),
                ('config', models.JSONField(blank=True, default=dict, null=True)),
                ('resolution_width', models.IntegerField(blank=True, default=1920, null=True)),
                ('resolution_height', models.IntegerField(blank=True, default=1080, null=True)),
                ('fps', models.IntegerField(blank=True, default=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
