# Generated by Django 5.1.6 on 2026-01-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_streaming',
            field=models.BooleanField(default=False, help_text='Whether MJPEG stream is active'),
        ),
    ]
