# Generated by Django 5.1.6 on 2026-01-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera_is_streaming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='is_processing',
        ),
        migrations.AddField(
            model_name='camera',
            name='ai_enabled',
            field=models.BooleanField(default=False, help_text='Whether AI inference is enabled for this camera'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='is_streaming',
            field=models.BooleanField(default=True, help_text='Whether streaming is enabled (auto-enabled on creation)'),
        ),
    ]
