# Generated by Django 5.1.6 on 2026-01-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_add_ai_enabled_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ptz_channel',
            field=models.IntegerField(default=1, help_text='PTZ channel number'),
        ),
        migrations.AddField(
            model_name='camera',
            name='ptz_enabled',
            field=models.BooleanField(default=False, help_text='Whether PTZ control is enabled for this camera'),
        ),
        migrations.AddField(
            model_name='camera',
            name='ptz_ip',
            field=models.CharField(blank=True, help_text='PTZ camera IP address (if different from RTSP)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='ptz_password',
            field=models.CharField(blank=True, help_text='PTZ camera password', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='ptz_preset_number',
            field=models.IntegerField(default=20, help_text='Default preset position number'),
        ),
        migrations.AddField(
            model_name='camera',
            name='ptz_tracking_enabled',
            field=models.BooleanField(default=True, help_text='Whether PTZ auto-tracking is enabled'),
        ),
        migrations.AddField(
            model_name='camera',
            name='ptz_username',
            field=models.CharField(blank=True, help_text='PTZ camera username', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='ptz_zoom_enabled',
            field=models.BooleanField(default=True, help_text='Whether PTZ zoom control is enabled'),
        ),
        migrations.AddField(
            model_name='camera',
            name='ptz_zoom_in_enabled',
            field=models.BooleanField(default=True, help_text='Whether zoom in is enabled'),
        ),
        migrations.AddField(
            model_name='camera',
            name='ptz_zoom_out_enabled',
            field=models.BooleanField(default=True, help_text='Whether zoom out is enabled'),
        ),
        migrations.AddField(
            model_name='camera',
            name='tracking_edge_margin_percent',
            field=models.FloatField(default=7.0, help_text='Edge margin as percentage of frame'),
        ),
        migrations.AddField(
            model_name='camera',
            name='tracking_enable_edge_filtering',
            field=models.BooleanField(default=True, help_text='Filter aircraft at frame edges'),
        ),
        migrations.AddField(
            model_name='camera',
            name='tracking_enable_size_filter',
            field=models.BooleanField(default=True, help_text='Filter out small aircraft'),
        ),
        migrations.AddField(
            model_name='camera',
            name='tracking_lock_only_mode',
            field=models.BooleanField(default=True, help_text='Only track currently locked aircraft'),
        ),
        migrations.AddField(
            model_name='camera',
            name='tracking_min_aircraft_width',
            field=models.IntegerField(default=10, help_text='Minimum aircraft width in pixels'),
        ),
        migrations.AddField(
            model_name='camera',
            name='tracking_min_consecutive_detections',
            field=models.IntegerField(default=5, help_text='Minimum detections before PTZ tracking'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(choices=[('ip', 'IP Camera'), ('rtsp', 'RTSP Stream'), ('usb', 'USB Camera'), ('file', 'Video File'), ('ptz', 'PTZ Camera')], default='rtsp', max_length=20),
        ),
        migrations.AlterField(
            model_name='camera',
            name='is_streaming',
            field=models.BooleanField(default=True, help_text='Whether WebSocket streaming is enabled'),
        ),
    ]
