# Generated by Django 5.1.6 on 2026-01-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_add_ptz_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ptz_zoom_config',
            field=models.JSONField(blank=True, default=list, help_text='Array of zoom rules: [{min_area, max_area, action, duration, speed, label}]', null=True),
        ),
    ]
